version: '2'
services:
    springboot141-app:
        image: springboot141
        external_links:
            - springboot141-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springboot141?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springboot141-mysql:
        extends:
            file: mysql.yml
            service: springboot141-mysql
