version: '2'
services:
    springboot141-mysql:
        container_name: springboot141-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/springboot141/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=springboot141
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
